      SUBROUTINE DB_TRN(UU,VV,WW,PP,FF,NF,
     &                  IGRFIL,MX,MY,MZ,ISTEP,TIME)
C
CD=== 概要 ===========================================================
C
CDT   DB_TRN:解析結果を図化ファイルに出力する
C
C==== 宣言 ===========================================================
C
      IMPLICIT NONE
C
cc      INCLUDE 'DOMAIN.h'
cc      INCLUDE 'MODELI.h'
cc      INCLUDE 'MODELR.h'
cc      INCLUDE 'TIMEI.h'
cc      INCLUDE 'TIMER.h'
C
CD    -- 引数 --
CD    UU(MX,MY,MZ)     : IN  : R*8 : x方向流速
CD    VV(MX,MY,MZ)     : IN  : R*8 : y方向流速
CD    WW(MX,MY,MZ)     : IN  : R*8 : z方向流速
CD    PP(MX,MY,MZ)     : IN  : R*8 : 圧力
CD    FF(MX,MY,MZ)     : IN  : R*8 : VOF関数F
CD    TT(MX,MY,MZ)     : IN  : R*8 : 温度
CD    CC(MX,MY,MZ)     : IN : R*8 : 濃度
CD    INDP(MX,MY,MZ)   : IN  : I*4 : z面の状態を示すインデックス
CD    NF(MX,MY,MZ)     : IN  : I*4 : セルの状態を示すインデックス
CD    KF(MX,MY)        : IN  : I*4 : 自由表面の位置を示すインデックス
C
      REAL(8),INTENT(INOUT)::UU(MX,MY,MZ),VV(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::WW(MX,MY,MZ),PP(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::FF(MX,MY,MZ)
ccc      REAL(8),INTENT(INOUT)::TT(MX,MY,MZ),CC(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::NF(MX,MY,MZ)
ccc      INTEGER,INTENT(INOUT)::INDP(MX,MY,MZ),KF(MX,MY)
      INTEGER,INTENT(INOUT)::IGRFIL
      INTEGER::MX,MY,MZ,MXM,MYM,MZM
      INTEGER::ISTEP
      REAL(8)::TIME
C
      INTEGER::I,I1,I2,J,J1,J2,K,K1,K2,NB
C
      MXM = MX -1
      MYM = MY -1
      MZM = MZ -1
C
C==== 実行 ===========================================================
C
CD    -- メッセージの出力 --
cccccc      WRITE(ILPFIL,9510) ISTEP,TIME
C
CD    -- 定数の設定 --
      I1=1
      J1=1
      K1=1
      I2=MXM-1
      J2=MYM-1
      K2=MZM-1
      NB=0
C
CD    -- 計算情報を出力 --
      WRITE(IGRFIL,ERR=9010) ISTEP,TIME
CDEBUG      WRITE(IGRFIL,*,ERR=9010) ISTEP
CDEBUG      WRITE(IGRFIL,*,ERR=9010) TIME
C 
CDEBUGCDEBUGCDEBUG      DO 100 J=2,MYM
CDEBUGCDEBUGCDEBUG      DO 110 I=2,MXM
CDEBUGCDEBUGCDEBUG      DO 120 K=2,MZM
CDEBUGCDEBUGCDEBUG        NF(I,J,K)=-1
CDEBUGCDEBUGCDEBUG        IF(INDP(I,J,K).EQ.1) THEN
CDEBUGCDEBUGCDEBUG          IF(K.GT.KF(I,J)) THEN
CDEBUGCDEBUGCDEBUG            NF(I,J,K)=8
CDEBUGCDEBUGCDEBUG          ELSE IF(K.EQ.KF(I,J)) THEN
CDEBUGCDEBUGCDEBUG            NF(I,J,K)=5
CDEBUGCDEBUGCDEBUG          ELSE
CDEBUGCDEBUGCDEBUG            NF(I,J,K)=0
CDEBUGCDEBUGCDEBUG          END IF
CDEBUGCDEBUGCDEBUG        END IF
CDEBUGCDEBUGCDEBUG  120 CONTINUE
CDEBUGCDEBUGCDEBUG  110 CONTINUE
CDEBUGCDEBUGCDEBUG  100 CONTINUE
C
CD    -- セルの状態を示すインデックスを出力 --
      WRITE(IGRFIL,ERR=9010) (((NF(I,J,K),I=2,MXM),J=2,MYM),K=2,MZM)
CDEBUG      DO 800 K=2,MZM
CDEBUG      DO 802 J=2,MYM
CDEBUG      DO 804 I=2,MXM
CDEBUG      WRITE(IGRFIL,*,ERR=9010) NF(I,J,K)
CDEBUG  804 CONTINUE
CDEBUG  802 CONTINUE
CDEBUG  800 CONTINUE
CD    -- 流速を出力 --
      WRITE(IGRFIL,ERR=9010)
     $   (((REAL(UU(I,J,K)),I=2,MX),J=2,MYM),K=2,MZM)
CDEBUG      DO 810 K=2,MZM
CDEBUG      DO 812 J=2,MYM
CDEBUG      DO 814 I=1,MXM
CDEBUG      WRITE(IGRFIL,*,ERR=9010) UU(I,J,K)
CDEBUG  814 CONTINUE
CDEBUG  812 CONTINUE
CDEBUG  810 CONTINUE
      WRITE(IGRFIL,ERR=9010)
     $   (((REAL(VV(I,J,K)),I=2,MXM),J=2,MY),K=2,MZM)
CDEBUG      DO 820 K=2,MZM
CDEBUG      DO 822 J=1,MYM
CDEBUG      DO 824 I=2,MXM
CDEBUG      WRITE(IGRFIL,*,ERR=9010) VV(I,J,K)
CDEBUG  824 CONTINUE
CDEBUG  822 CONTINUE
CDEBUG  820 CONTINUE
      WRITE(IGRFIL,ERR=9010)
     $   (((REAL(WW(I,J,K)),I=2,MXM),J=2,MYM),K=2,MZ)
CDEBUG      DO 830 K=1,MZM
CDEBUG      DO 832 J=2,MYM
CDEBUG      DO 834 I=2,MXM
CDEBUG      WRITE(IGRFIL,*,ERR=9010) WW(I,J,K)
CDEBUG  834 CONTINUE
CDEBUG  832 CONTINUE
CDEBUG  830 CONTINUE
CD    -- 圧力を出力 --
!!!      WRITE(IGRFIL,ERR=9010) (((PP(I,J,K),I=2,MXM),J=2,MYM),K=2,MZM)
CDEBUG      DO 840 K=2,MZM
CDEBUG      DO 842 J=2,MYM
CDEBUG      DO 844 I=2,MXM
CDEBUG      WRITE(IGRFIL,*,ERR=9010) PP(I,J,K)
CDEBUG  844 CONTINUE
CDEBUG  842 CONTINUE
CDEBUG  840 CONTINUE
CD    -- VOF関数Fを出力 --
      WRITE(IGRFIL,ERR=9010) (((FF(I,J,K),I=2,MXM),J=2,MYM),K=2,MZM)
CDEBUG      DO 850 K=2,MZM
CDEBUG      DO 852 J=2,MYM
CDEBUG      DO 854 I=2,MXM
CDEBUG      WRITE(IGRFIL,*,ERR=9010) FF(I,J,K)
CDEBUG  854 CONTINUE
CDEBUG  852 CONTINUE
CDEBUG  850 CONTINUE
CD    -- 温度を出力 --
CDEBUG      IF (LTEMP.NE.0) THEN
CDEBUG        WRITE(IGRFIL,ERR=9010)
CDEBUG     $      (((REAL(TT(I,J,K)),I=2,MXM),J=2,MYM),K=2,MZM)
CDEBUGCDEBUG        DO 860 K=2,MZM
CDEBUGCDEBUG        DO 862 J=2,MYM
CDEBUGCDEBUG        DO 864 I=2,MXM
CDEBUGCDEBUG        WRITE(IGRFIL,*,ERR=9010) TT(I,J,K)
CDEBUGCDEBUG  864   CONTINUE
CDEBUGCDEBUG  862   CONTINUE
CDEBUGCDEBUG  860   CONTINUE
CDEBUG      ENDIF
CDEBUGCD    -- 濃度を出力 --
CDEBUG      IF (LCONC.NE.0) THEN
CDEBUG        WRITE(IGRFIL,ERR=9010)
CDEBUG     $      (((REAL(CC(I,J,K)),I=2,MXM),J=2,MYM),K=2,MZM)
CDEBUGCDEBUG        DO 870 K=2,MZM
CDEBUGCDEBUG        DO 872 J=2,MYM
CDEBUGCDEBUG        DO 874 I=2,MXM
CDEBUGCDEBUG        WRITE(IGRFIL,*,ERR=9010) CC(I,J,K)
CDEBUGCDEBUG  874   CONTINUE
CDEBUGCDEBUG  872   CONTINUE
CDEBUGCDEBUG  870   CONTINUE
CDEBUG      END IF
C
C     -- 実行文の終了 --
 9000 CONTINUE
      GOTO 9999
C
C==== ファイル関連エラー処理 =========================================
C
 9010 CONTINUE
      WRITE(*,*) 'DB_TRN WRITE ERROR (data.grp).'
      GOTO 9999
C
C==== フォーマット文 =================================================
C
 9510 FORMAT( ' ','>> FILE-GRP : OUT : STEP=',I6,' : TIME= ',1PE12.5)
C
C==== 終了 ===========================================================
C
 9999 CONTINUE
      RETURN
      END
